filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /home/product-inventory-management-system/logs/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "inventory-service-logs"

setup:
  ilm:
    enabled: false
  template:
    name: "inventory-service"
    pattern: "inventory-service-*"
    settings:
      index.number_of_shards: 1
      index.number_of_replicas: 1
