filebeat.inputs:
  - type: docker
    enabled: true
    containers:
      path: "/home/product-inventory-management-system/logs/*.log"
      stream: "all"
      ids:
        - "inventory_service"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "inventory-service"
# output.logstash:
#   hosts: ["logstash:5044"]
